////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
//= Simplified Hibernate ORM with Panache
= Hibernate ORM 和 Panache

include::./attributes.adoc[]
:config-file: application.properties

//Hibernate ORM is the de facto JPA implementation and offers you the full breadth of an Object Relational Mapper.
//It makes complex mappings possible, but it does not make simple and common mappings trivial.
//Hibernate ORM with Panache focuses on making your entities trivial and fun to write in Quarkus.
//
Hibernate ORM 是 JPA 的一种实现，它为您提供了对象关系映射。它使复杂的映射关系成为可能。带有 Panache 的 Hibernate ORM 专注于实体在 Quarkus 中的使用。



//== First: an example
== 首先一个简单的例子
//What we're doing in Panache is to allow you to write your Hibernate ORM entities like this:
在 Panache 中允许您这样编写 Hibernate ORM 实体：

[source,java]
----
public enum Status {
    Alive,
    Deceased
}

@Entity
public class Person extends PanacheEntity {
    public String name;
    public LocalDate birth;
    public Status status;

    public static Person findByName(String name){
        return find("name", name).firstResult();
    }

    public static List<Person> findAlive(){
        return list("status", Status.Alive);
    }

    public static void deleteStefs(){
        delete("name", "Stef");
    }
}
----

//You have noticed how much more compact and readable the code is?
//Does this look interesting? Read on!
您是否注意到代码更加紧凑和可读，这看起来有趣吗？请继续阅读。

//NOTE: the `list()` method might be surprising at first. It takes fragments of HQL (JP-QL) queries and contextualizes the rest. That makes for very concise but yet readable code.
NOTE: `list()` 方法起初可能有些令人惊讶，它采用 HQL(JP-QL) 查询片段作为参数将其他内容上下文化，这使得代码非常简洁，但不丢失可读性。

//NOTE: what was described above is essentially the link:https://www.martinfowler.com/eaaCatalog/activeRecord.html[active record pattern], sometimes just called the entity pattern.
//Hibernate with Panache also allows for the use of the more classical link:https://martinfowler.com/eaaCatalog/repository.html[repository pattern] via `PanacheRepository`.
NOTE: 上面描述的本质是 link:https://www.martinfowler.com/eaaCatalog/activeRecord.html[活动记录模式] ，有时也称之为实体模式。 Hibernate ORM 和 Panache 也允许  link:https://martinfowler.com/eaaCatalog/repository.html[仓库模式]


//== Solution
== 源码获取

//We recommend that you follow the instructions in the next sections and create the application step by step.
//However, you can go right to the completed example.
我们建议您按照本教程的说明一步一步完成应用程序的制作。但是，您可以直接跳转到完整实例。

//Clone the Git repository: `git clone {quickstarts-clone-url}`, or download an {quickstarts-archive-url}[archive].
克隆 git 仓库：`git clone {quickstarts-clone-url}` 或者下载  {quickstarts-archive-url}[源码].

//The solution is located in the `hibernate-orm-panache-quickstart` {quickstarts-tree-url}/hibernate-orm-panache-quickstart[directory].

本教程源码位于 {quickstarts-tree-url}/hibernate-orm-panache-quickstart[地址].


//== Setting up and configuring Hibernate ORM with Panache
== 配置 Hibernate ORM 和 Panache

//To get started:
执行顺序：

//* add your settings in `{config-file}`
* 将您的配置添加到 `{config-file}` 。
//* annotate your entities with `@Entity`
* 使用 `@Entity` 注解标记实体
//* make your entities extend `PanacheEntity` (optional if you are using the repository pattern)
* 让实体继承 `PanacheEntity` (可选项，如果您想要使用仓库模式)

//Follow the xref:hibernate-orm.adoc#setting-up-and-configuring-hibernate-orm[Hibernate set-up guide for all configuration].
按照 xref:hibernate-orm-CN.adoc#setting-up-and-configuring-hibernate-orm[Hibernate 配置教程]

//In your build file, add the following dependencies:
在您的项目中依赖项如下：

//* the Hibernate ORM with Panache extension
* Hibernate ORM 和 Panache 扩展
//* your JDBC driver extension (`quarkus-jdbc-postgresql`, `quarkus-jdbc-h2`, `quarkus-jdbc-mariadb`, ...)
* JDBC 驱动拓展 (`quarkus-jdbc-postgresql`, `quarkus-jdbc-h2`, `quarkus-jdbc-mariadb`, ...)

[source,xml,role="primary asciidoc-tabs-target-sync-cli asciidoc-tabs-target-sync-maven"]
.pom.xml
----
<!-- Hibernate ORM specific dependencies -->
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-hibernate-orm-panache</artifactId>
</dependency>

<!-- JDBC driver dependencies -->
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jdbc-postgresql</artifactId>
</dependency>
----

[source,gradle,role="secondary asciidoc-tabs-target-sync-gradle"]
.build.gradle
----
// Hibernate ORM specific dependencies
implementation("io.quarkus:quarkus-hibernate-orm-panache")

// JDBC driver dependencies
implementation("io.quarkus:quarkus-jdbc-postgresql")
----

//Then add the relevant configuration properties in `{config-file}`.
然后在 `{config-file}` 文件中添加配置信息：

[source,properties]
----
# configure your datasource
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = sarah
quarkus.datasource.password = connor
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/mydatabase

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation = drop-and-create
----

//== Solution 1: using the active record
== 方案1: 使用活动记录模式

//=== Defining your entity
=== 定义你的实体

//To define a Panache entity, simply extend `PanacheEntity`, annotate it with `@Entity` and add your
//columns as public fields:
首先需要定义 Panache 实体，这样的实体只需要继承 `PanacheEntity` , 使用注解 `@Entity` 标记并且添加属性字段。

[source,java]
----
@Entity
public class Person extends PanacheEntity {
    public String name;
    public LocalDate birth;
    public Status status;
}
----

//You can put all your JPA column annotations on the public fields. If you need a field to not be persisted, use the
//`@Transient` annotation on it. If you need to write accessors, you can:

您可以将所有 JPA 注解放在字段上。如果宁想要忽略某些字段可以使用 `@Transient` 注解

[source,java]
----
@Entity
public class Person extends PanacheEntity {
    public String name;
    public LocalDate birth;
    public Status status;

    // return name as uppercase in the model
    public String getName(){
        return name.toUpperCase();
    }

    // store all names in lowercase in the DB
    public void setName(String name){
        this.name = name.toLowerCase();
    }
}
----

//And thanks to our field access rewrite, when your users read `person.name` they will actually call your `getName()` accessor,
//and similarly for field writes and the setter.
//This allows for proper encapsulation at runtime as all fields calls will be replaced by the corresponding getter/setter calls.

由于我们对访问字段进行了自定义处理，当您的用户在获取 `person.name` 属性时会调用 `getName` ，对于数据字段的写入也进行了重写相关操作都会执行具体的set方法。在 Hibernate ORM 中允许您对 get/set 方法进行适当的封装。

//=== Most useful operations
=== 有用的操作

//Once you have written your entity, here are the most common operations you will be able to perform:
在编写实体后，您可以执行一下常见操作

[source,java]
----
// 创建 Person 对象
Person person = new Person();
person.name = "Stef";
person.birth = LocalDate.of(1910, Month.FEBRUARY, 1);
person.status = Status.Alive;

// 持久化
person.persist();

// 注意，一旦持久化，您无需显式保存实体：所有修改都会在事务提交时自动持久化。


// 检查是否持久化
if(person.isPersistent()){
    // 删除数据
    person.delete();
}

// 获取所有 Person
List<Person> allPersons = Person.listAll();

// 根据id查询 Person
person = Person.findById(personId);

// 进行可能存在的查询，在查询结果不存在时抛出异常
Optional<Person> optional = Person.findByIdOptional(personId);
person = optional.orElseThrow(() -> new NotFoundException());

// 查询 status 为 Status.Alive 的 Person
List<Person> livingPersons = Person.list("status", Status.Alive);

// 求 Person 数量
long countAll = Person.count();

// 统计 status 为 Status.Alive 的数量
long countAlive = Person.count("status", Status.Alive);

// 删除 status 为 Status.Alive 的数量
Person.delete("status", Status.Alive);

// 删除所有
Person.deleteAll();

// 根据 id 删除
boolean deleted = Person.deleteById(personId);

// 更新数据
Person.update("name = 'Mortal' where status = ?1", Status.Alive);

----

//All `list` methods have equivalent `stream` versions.
所有 `list` 方法都有等价的 `stream` 版本的方法

[source,java]
----
try (Stream<Person> persons = Person.streamAll()) {
    List<String> namesButEmmanuels = persons
        .map(p -> p.name.toLowerCase() )
        .filter( n -> ! "emmanuel".equals(n) )
        .collect(Collectors.toList());
}
----

//NOTE: The `stream` methods require a transaction to work. +
//As they perform I/O operations, they should be closed via the `close()` method or via a try-with-resource to close the underlying `ResultSet`.
//If not, you will see warnings from Agroal that will close the underlying `ResultSet` for you.
NOTE: 这些 `stream` 需要一个事务对象才能够工作。当它执行 I/O 操作时，他们应该通过 `close` 方法或者通过 try-with-resource 来关闭底层的 `ResultSet` 对象。如果没有，您将看到来自 Agroal 的经过，该警告将希望您关闭 `ResultSet` 对象。

//=== Adding entity methods
=== 添加实体方法

Add custom queries on your entities inside the entities themselves.
That way, you and your co-workers can find them easily, and queries are co-located with the object they operate on.
Adding them as static methods in your entity class is the Panache Active Record way.

在实体内部允许添加自定义方法完成自定义查询操作。这样，您和您的同时可以轻松找到他们，并且查询与操作对象位于同一个位置，将它们作为静态方法添加到实体类中这样的方式我们称之为 Panache Active Record。

[source,java]
----
@Entity
public class Person extends PanacheEntity {
    public String name;
    public LocalDate birth;
    public Status status;

    public static Person findByName(String name){
        return find("name", name).firstResult();
    }

    public static List<Person> findAlive(){
        return list("status", Status.Alive);
    }

    public static void deleteStefs(){
        delete("name", "Stef");
    }
}
----

//== Solution 2: using the repository pattern
== 方案2: 使用仓库模式


//=== Defining your entity'
=== 定义您的实体

//When using the repository pattern, you can define your entities as regular JPA entities.
使用仓库模式时，您可以将实体定义为常规的 JPA 实体。

[source,java]
----
@Entity
public class Person {
    @Id @GeneratedValue private Long id;
    private String name;
    private LocalDate birth;
    private Status status;

    public Long getId(){
        return id;
    }
    public void setId(Long id){
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public LocalDate getBirth() {
        return birth;
    }
    public void setBirth(LocalDate birth) {
        this.birth = birth;
    }
    public Status getStatus() {
        return status;
    }
    public void setStatus(Status status) {
        this.status = status;
    }
}
----

//TIP: If you don't want to bother defining getters/setters for your entities, you can make them extend `PanacheEntityBase` and
//Quarkus will generate them for you. You can even extend `PanacheEntity` and take advantage of the default ID it provides.
TIP: 如果您不想飞行的为实体定义 getters/setters 您可以继承 `PanacheEntityBase` ，Quarkus 将为您生成它们，您甚至可以继承 `PanacheEntity` 使用它来提供默认的ID。


//=== Defining your repository
=== 定义您的仓库

//When using Repositories, you get the exact same convenient methods as with the active record pattern, injected in your Repository,
//by making them implements `PanacheRepository`:

使用 Repositories 时，您可以获得与活动记录模式完全相同的便捷方法，通过实现 `PanacheRepository` 接口来获取方法

[source,java]
----
@ApplicationScoped
public class PersonRepository implements PanacheRepository<Person> {

   // put your custom logic here as instance methods

   public Person findByName(String name){
       return find("name", name).firstResult();
   }

   public List<Person> findAlive(){
       return list("status", Status.Alive);
   }

   public void deleteStefs(){
       delete("name", "Stef");
  }
}
----

//All the operations that are defined on `PanacheEntityBase` are available on your repository, so using it
//is exactly the same as using the active record pattern, except you need to inject it:

常规操作都在 `PanacheEntityBase` 类中有相关标记，因此使用它与活动记录模式相同，除了您需要注入它

[source,java]
----
@Inject
PersonRepository personRepository;

@GET
public long count(){
    return personRepository.count();
}
----

//=== Most useful operations
=== 有用的操作

//Once you have written your repository, here are the most common operations you will be able to perform:
编写完成仓库后，您可以执行一下常见操作：

[source,java]
----
// 创建 Person 对象
Person person = new Person();
person.setName("Stef");
person.setBirth(LocalDate.of(1910, Month.FEBRUARY, 1));
person.setStatus(Status.Alive);

// 持久化 Person 对象
personRepository.persist(person);

// 注意，一旦持久化，您无需显式保存实体：所有修改都会在事务提交时自动持久化。

// 检查是否持久化
if(personRepository.isPersistent(person)){
    // 删除数据
    personRepository.delete(person);
}

// 获取所有 Person
List<Person> allPersons = personRepository.listAll();

// 根据id查询 Person
person = personRepository.findById(personId);

// 进行可能存在的查询，在查询结果不存在时抛出异常
Optional<Person> optional = personRepository.findByIdOptional(personId);
person = optional.orElseThrow(() -> new NotFoundException());

// 查询 status 为 Status.Alive 的 Person
List<Person> livingPersons = personRepository.list("status", Status.Alive);

// 求 Person 数量
long countAll = personRepository.count();

// 统计 status 为 Status.Alive 的数量
long countAlive = personRepository.count("status", Status.Alive);

// 删除 status 为 Status.Alive 的数量
personRepository.delete("status", Status.Alive);

// 删除所有
personRepository.deleteAll();

// 根据 id 删除
boolean deleted = personRepository.deleteById(personId);

// 更新数据
personRepository.update("name = 'Mortal' where status = ?1", Status.Alive);

----

//All `list` methods have equivalent `stream` versions.
所有 `list` 方法都有等价的 `stream` 版本的方法

[source,java]
----
Stream<Person> persons = personRepository.streamAll();
List<String> namesButEmmanuels = persons
    .map(p -> p.name.toLowerCase() )
    .filter( n -> ! "emmanuel".equals(n) )
    .collect(Collectors.toList());
----

//NOTE: The `stream` methods require a transaction to work.
NOTE: 这些 `stream` 需要一个事务对象才能够工作。

//NOTE: The rest of the documentation show usages based on the active record pattern only,
//but keep in mind that they can be performed with the repository pattern as well.
//The repository pattern examples have been omitted for brevity.

NOTE: 文档的其他部分仅演示基于活动记录模式的用法，注意，他们也可以使用仓库模式执行。为了简洁期间，省略了仓库模式相关的代码。

//== Writing a JAX-RS resource
== 编写 JAX-RS 资源

//First, include one of the RESTEasy extensions to enable JAX-RS endpoints, for example, add the `io.quarkus:quarkus-resteasy-jackson` dependency for JAX-RS and JSON support.
首先，需要引入 RESTEasy 拓展以启动 JAX-RS 端点，例如，添加 `io.quarkus:quarkus-resteasy-jackson` 依赖项，该依赖项支持 JAX-RS 和 JSON 。

//Then, you can create the following resource to create/read/update/delete your Person entity:
然后，您可以创建资源对象，用于新增、读取、更新和删除 Person 实体：

[source,java]
----
@Path("/persons")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class PersonResource {

    @GET
    public List<Person> list() {
        return Person.listAll();
    }

    @GET
    @Path("/{id}")
    public Person get(@PathParam("id") Long id) {
        return Person.findById(id);
    }

    @POST
    @Transactional
    public Response create(Person person) {
        person.persist();
        return Response.created(URI.create("/persons/" + person.id)).build();
    }

    @PUT
    @Path("/{id}")
    @Transactional
    public Person update(@PathParam("id") Long id, Person person) {
        Person entity = Person.findById(id);
        if(entity == null) {
            throw new NotFoundException();
        }

        // map all fields from the person parameter to the existing entity
        entity.name = person.name;

        return entity;
    }

    @DELETE
    @Path("/{id}")
    @Transactional
    public void delete(@PathParam("id") Long id) {
        Person entity = Person.findById(id);
        if(entity == null) {
            throw new NotFoundException();
        }
        entity.delete();
    }

    @GET
    @Path("/search/{name}")
    public Person search(@PathParam("name") String name) {
        return Person.findByName(name);
    }

    @GET
    @Path("/count")
    public Long count() {
        return Person.count();
    }
}
----

//NOTE: Be careful to use the `@Transactional` annotation on the operations that modify the database,
//you can add the annotation at the class level for simplicity purpose.

NOTE: 注意 `@Transactional` 需要在修改数据库操作上使用注解，为了简单期间，您可以在类级别添加该注解。

//== Advanced Query
== 高级查询

//=== Paging
=== 查询

//You should only use `list` and `stream` methods if your table contains small enough data sets. For larger data
//sets you can use the `find` method equivalents, which return a `PanacheQuery` on which you can do paging:
如果您的数据表数量足够小，您应该使用 `list` 和 `stream` 相关方法。 `stream` 对于较大数据集，您可以使用 `find` 等方法，它返回一个 `PanacheQuery` 对象，您可以在其纸上使用分页方法：

[source,java]
----
// 创建一个分页查询
PanacheQuery<Person> livingPersons = Person.find("status", Status.Alive);

// 分页数量为 25
livingPersons.page(Page.ofSize(25));

// 获取数量
List<Person> firstPage = livingPersons.list();

// 获取第二页
List<Person> secondPage = livingPersons.nextPage().list();

// 获取第7页
List<Person> page7 = livingPersons.page(Page.of(7, 25)).list();

// 获取总量
int numberOfPages = livingPersons.pageCount();

// 获取总量
long count = livingPersons.count();

// 链式调用
return Person.find("status", Status.Alive)
    .page(Page.ofSize(25))
    .nextPage()
    .stream()
----

//The `PanacheQuery` type has many other methods to deal with paging and returning streams.
`PanacheQuery` 类型有许多其他方法来处理分页和返回流。

//=== Using a range instead of pages
=== 使用范围查询

`PanacheQuery` also allows range-based queries.

`PanacheQuery` 允许基于范围查询

[source,java]
----
// 创建查询
PanacheQuery<Person> livingPersons = Person.find("status", Status.Alive);

// 让它使用一个范围：从索引 0 开始直到索引 24（包括）
livingPersons.range(0, 24);

// 获取范围内的数据
List<Person> firstRange = livingPersons.list();

// 要获得下一个范围，您需要再次调用范围
List<Person> secondRange = livingPersons.range(25, 49).list();
----

[WARNING]
====
//You cannot mix ranges and pages: if you use a range, all methods that depend on having a current page will throw an `UnsupportedOperationException`;
//you can switch back to paging using `page(Page)` or `page(int, int)`.

您不能够混合使用 range 和 page ，如果您使用了 range 并且依赖 page 会抛出 `UnsupportedOperationException` 异常，如果出现该异常建议切换回 page。
====

//=== Sorting
=== 排序

//All methods accepting a query string also accept the following simplified query form:
所有查询都接收以字符串的心声进行排序查询：

[source,java]
----
List<Person> persons = Person.list("order by name,birth");
----

//But these methods also accept an optional `Sort` parameter, which allows your to abstract your sorting:
这些方法也接受一个可选的 `Sort` 参数，它允许您抽象排序

[source,java]
----
List<Person> persons = Person.list(Sort.by("name").and("birth"));

// and with more restrictions
List<Person> persons = Person.list("status", Sort.by("name").and("birth"), Status.Alive);
----

//The `Sort` class has plenty of methods for adding columns and specifying sort direction.
`Sort` 有很多用于添加列或者指定排序方向的方法。

//=== Simplified queries
=== 简化查询

//Normally, HQL queries are of this form: `from EntityName [where ...] [order by ...]`, with optional elements
//at the end.
通常 HQL 查询采用以下形式编写：  `from EntityName [where ...] [order by ...]`

//If your select query does not start with `from`, we support the following additional forms:
如果您的查询不以 `from` 开头，我们将附加以下形式：


//- `order by ...` which will expand to `from EntityName order by ...`
- 在 `from EntityName order by ...` 后添加 `order by ...`
//- `<singleColumnName>` (and single parameter) which will expand to `from EntityName where <singleColumnName> = ?`
- 如果是单列查询会以：`from EntityName where <singleColumnName> = ?` 形式添加
//- `<query>` will expand to `from EntityName where <query>`
- 在`from EntityName where <query>` 中添加查询条件

//If your update query does not start with `update`, we support the following additional forms:
如果您的更新不以 `update` 开头，我们将附加以下形式：

//- `from EntityName ...` which will expand to `update from EntityName ...`
- 将 `from EntityName ...` 扩展为 `update from EntityName ...`
//- `set? <singleColumnName>` (and single parameter) which will expand to `update from EntityName set <singleColumnName> = ?`
- 如果是单列更新将会以 `update from EntityName set <singleColumnName> = ?` 形式添加
//- `set? <update-query>` will expand to `update from EntityName set <update-query>`
- 将 `set? <update-query>` 扩展为 `update from EntityName set <update-query>`

If your delete query does not start with `delete`, we support the following additional forms:

- `from EntityName ...` which will expand to `delete from EntityName ...`
- `<singleColumnName>` (and single parameter) which will expand to `delete from EntityName where <singleColumnName> = ?`
- `<query>` will expand to `delete from EntityName where <query>`

//NOTE: You can also write your queries in plain
//link:https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#hql[HQL]:
NOTE: 您还可以通过编写普通 link:https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#hql[HQL] 进行查询

[source,java]
----
Order.find("select distinct o from Order o left join fetch o.lineItems");
Order.update("update from Person set name = 'Mortal' where status = ?", Status.Alive);
----

//=== Named queries
=== 命名查询

//You can reference a named query instead of a (simplified) HQL query by prefixing its name with the '#' character. You can also use named queries for count, update and delete queries.
您可以通过再起名称前添加 `#` 符号来进行简化的命名查询，而不是简化 HQL 查询。您还可以将命名查询用在计数、更新和删除操作上

[source,java]
----
@Entity
@NamedQueries({
    @NamedQuery(name = "Person.getByName", query = "from Person where name = ?1"),
    @NamedQuery(name = "Person.countByStatus", query = "select count(*) from Person p where p.status = :status"),
    @NamedQuery(name = "Person.updateStatusById", query = "update Person p set p.status = :status where p.id = :id"),
    @NamedQuery(name = "Person.deleteById", query = "delete from Person p where p.id = ?1")
})

public class Person extends PanacheEntity {
    public String name;
    public LocalDate birth;
    public Status status;

    public static Person findByName(String name){
        return find("#Person.getByName", name).firstResult();
    }

    public static long countByStatus(Status status) {
        return count("#Person.countByStatus", Parameters.with("status", status).map());
    }

    public static long updateStatusById(Status status, long id) {
        return update("#Person.updateStatusById", Parameters.with("status", status).and("id", id));
    }

    public static long deleteById(long id) {
        return delete("#Person.deleteById", id);
    }
}
----

[WARNING]
====
//Named queries can only be defined inside your JPA entity classes (being the Panache entity class, or the repository parameterized type),
//or on one of its super classes.
命名查询只能在您的 JPA 实体类（作为 Panache 实体类或者仓库模式的泛型类）内部或者其超类上定义。
====

//=== Query parameters
=== 参数查询

//You can pass query parameters by index (1-based) as shown below:
你可以按索引（从1开始）传递参数，如下所示

[source,java]
----
Person.find("name = ?1 and status = ?2", "stef", Status.Alive);
----

//Or by name using a `Map`:
或者按名称传递参数，这样需要使用 `Map` 结构，示例如下：

[source,java]
----
Map<String, Object> params = new HashMap<>();
params.put("name", "stef");
params.put("status", Status.Alive);
Person.find("name = :name and status = :status", params);
----

//Or using the convenience class `Parameters` either as is or to build a `Map`:
或者使用 `Parameters` 类来构建 `Map` 结构

[source,java]
----
// generate a Map
Person.find("name = :name and status = :status",
         Parameters.with("name", "stef").and("status", Status.Alive).map());

// use it as-is
Person.find("name = :name and status = :status",
         Parameters.with("name", "stef").and("status", Status.Alive));
----

//Every query operation accepts passing parameters by index (`Object...`), or by name (`Map<String,Object>` or `Parameters`).
每个查询操作都接受通过索引 (`Object...`) 或名称  (`Map<String,Object>` or `Parameters`) 的方式传递参数

//=== Query projection
=== 查询映射

Query projection can be done with the `project(Class)` method on the `PanacheQuery` object that is returned by the `find()` methods.
查询映射对象可以通过 `project(Class)` 方法将 `PanacheQuery` 对象的 `find` 方法进行处理。

//You can use it to restrict which fields will be returned by the database.
您可以使用它来限制数据库返回哪些字段。

//Hibernate will use **DTO projection** and generate a SELECT clause with the attributes from the projection class.
//This is also called **dynamic instantiation** or **constructor expression**, more info can be found on the Hibernate guide:
//link:https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#hql-select-clause[hql select clause]

Hibernate 将使用 **DTO** 映射并生成一个 SELECT 子句。这称为动态实例化（**dynamic instantiation**）或构造函数表达式（**constructor expression**），更多信息可以查看 link:https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#hql-select-clause[HQL SELECT 子句]



The projection class needs to be a valid Java Bean and have a constructor that contains all its attributes, this constructor will be used to
instantiate the projection DTO instead of using the entity class. This class must have a matching constructor with all the class attributes as parameters.

映射类需要是一个有效的 Java Bean 并且有一个包含所有属性的构造函数，这个构造函数将用于实例化映射对象，而不是使用实体类。此类不许有匹配的构造函数，并将所有属性作为构造参数。

[source,java]
----
import io.quarkus.runtime.annotations.RegisterForReflection;

@RegisterForReflection // <1>
public class PersonName {
    public final String name; // <2>

    public PersonName(String name){ // <3>
        this.name = name;
    }
}

// only 'name' will be loaded from the database
PanacheQuery<PersonName> query = Person.find("status", Status.Alive).project(PersonName.class);
----
//<1> The `@RegisterForReflection` annotation instructs Quarkus to keep the class and its members during the native compilation. More details about the `@RegisterForReflection` annotation can be found on  the xref:writing-native-applications-tips.adoc#registerForReflection[native application tips] page.
<1>  `@RegisterForReflection` 注解表示 Quarkus 在编译期间保留类以及成员变量，更多关于 `@RegisterForReflection` 注解的信息可以查看 xref:writing-native-applications-tips-CN.adoc#registerForReflection[原生应用提示] 文档
//<2> We use public fields here, but you can use private fields and getters/setters if you prefer.
<2> 在这里使用 public 修饰字段，如果您愿意可以使用 private 修饰字段和 getters/setters
//<3> This constructor will be used by Hibernate, it must be the only constructor in your class and have all the class attributes as parameters.
<3> 这个构造函数将被 Hibernate 使用，它必须是这个类中的唯一构造函数，并且具有所有成员变量作为构造参数


[WARNING]
====
//The implementation of the `project(Class)` method uses the constructor's parameter names to build the select clause of the query,
//so the compiler must be configured to store parameter names inside the compiled class.
//This is enabled by default if you are using the Quarkus Maven archetype. If you are not using it, add the property `<maven.compiler.parameters>true</maven.compiler.parameters>` to your `pom.xml`.
`project(Class)` 方法的实现使用构造函数的参数名称来构件 SELECT 子句，因此必须将编译器配置为：在编译后的类中存储参数名称。如果您使用 Quarkus Maven 骨架工程，则默认开启此功能。如果您没有使用 Quarkus Maven 骨架工程，请添加 `<maven.compiler.parameters>true</maven.compiler.parameters>` 属性到您的 `pom.xml` 文件.
====

//If in the DTO projection object you have a field from a referenced entity, you can use the `@ProjectedFieldName` annotation to provide the path for the SELECT statement.
如果在映射对象中有来自引用实体的字段，则可以使用 `@ProjectedFieldName` 注解为 SELECT 提供搜索路径。

[source,java]
----
@Entity
public class Dog extends PanacheEntity {
    public String name;
    public String race;
    @ManyToOne
    public Person owner;
}

@RegisterForReflection
public class DogDto {
    public String name;
    public String ownerName;

    public DogDto(String name, @ProjectedFieldName("owner.name") String ownerName) {  // <1>
        this.name = name;
        this.ownerName = ownerName;
    }
}

PanacheQuery<DogDto> query = Dog.findAll().project(DogDto.class);
----
//<1> The `ownerName` DTO constructor's parameter will be loaded from the `owner.name` HQL property.
<1> 构造函数中 `ownerName` 的取值将从 HQL 中的 `owner.name` 上获取。

//== Multiple Persistence Units
== 多单元持久化

//The support for multiple persistence units is described in detail in xref:hibernate-orm.adoc#multiple-persistence-units[the Hibernate ORM guide].
在 xref:hibernate-orm-CN.adoc#multiple-persistence-units[Hibernate ORM 教程] 中详细描述了 Hibernate 对多单元持久化的支持。使用 Panache 实现起来很简单：
//
//When using Panache, things are simple:
//
//* A given Panache entity can be attached to only a single persistence unit.
* 给定的 Panache 实体只能附加到单个持久化单元
//* Given that, Panache already provides the necessary plumbing to transparently find the appropriate `EntityManager` associated to a Panache entity.
* Panache 提供了必要的通道来找到与 Panache 实体联动的 `EntityManager`

//== Transactions
== 事务

//Make sure to wrap methods modifying your database (e.g. `entity.persist()`) within a transaction. Marking a
//CDI bean method `@Transactional` will do that for you and make that method a transaction boundary. We recommend doing
//so at your application entry point boundaries like your REST endpoint controllers.
确保修改数据库相关操作的方法封装在事务中（例如 `entity.persist()` ）。使用 `@Transactional` 注解标记 CDI Bean 方法，它将为您完成事务处理。我们建议在您的程序入口使用（例如 REST 端点控制器）

//JPA batches changes you make to your entities and sends changes (it's called flush) at the end of the transaction or before a query.
//This is usually a good thing as it's more efficient.
//But if you want to check optimistic locking failures, do object validation right away or generally want to get immediate feedback, you can force the flush operation by calling `entity.flush()` or even use `entity.persistAndFlush()` to make it a single method call. This will allow you to catch any `PersistenceException` that could occur when JPA send those changes to the database.
//Remember, this is less efficient so don't abuse it.
//And your transaction still has to be committed.

JPA 会批量处理您对实体所做的变化，并在事务结束或查询之前发送变化（称之为 *刷新* ）。这通常情况下是一件耗时，因为它更加有效。但是如果您想检查乐观锁失败或立即进行对象验证，您可以通过强制调用刷新操作（执行 `entity.flush()`  方法）或者使用 `entity.persistAndFlush()` 方法。这允许您捕获 `PersistenceException` 用来收集 JPA 与数据库交互是发送的异常情况。请记住，这样效率较低，请不要滥用它，而且您的事务仍然需要提交。

//Here is an example of the usage of the flush method to allow making a specific action in case of `PersistenceException`:
以下是 `flush` 方法的使用示例：

[source,java]
----
@Transactional
public void create(Parameter parameter){
    try {
        //Here I use the persistAndFlush() shorthand method on a Panache repository to persist to database then flush the changes.
        return parameterRepository.persistAndFlush(parameter);
    }
    catch(PersistenceException pe){
        LOG.error("Unable to create the parameter", pe);
        //in case of error, I save it to disk
        diskPersister.save(parameter);
    }
}
----

//== Lock management
== 锁管理

//Panache provides direct support for database locking with your entity/repository, using `findById(Object, LockModeType)` or `find().withLock(LockModeType)`.

Panache 中使用 `findById(Object, LockModeType)` 或者 `find().withLock(LockModeType)` 支持传入锁

//The following examples are for the active record pattern, but the same can be used with repositories.
以活动记录模式为例，锁的使用如下，这个方式同样适用于仓库模式

//=== First: Locking using findById().
=== 第一： 锁定 findById 方法

[source,java]
----
public class PersonEndpoint {

    @GET
    @Transactional
    public Person findByIdForUpdate(Long id){
        Person p = Person.findById(id, LockModeType.PESSIMISTIC_WRITE);
        //do something useful, the lock will be released when the transaction ends.
        return person;
    }

}
----

//=== Second: Locking in a find().
=== 第二： 锁定 find 方法

[source,java]
----
public class PersonEndpoint {

    @GET
    @Transactional
    public Person findByNameForUpdate(String name){
        Person p = Person.find("name", name).withLock(LockModeType.PESSIMISTIC_WRITE).findOne();
        //do something useful, the lock will be released when the transaction ends.
        return person;
    }

}
----

//Be careful that locks are released when the transaction ends, so the method that invokes the lock query must be annotated with the `@Transactional` annotation.
注意，事务结束时灰释放所，因此调用所查询的方法必须使用 `@Transactional` 注解。

//== Custom IDs
== 自定义 ID

//IDs are often a touchy subject, and not everyone's up for letting them handled by the framework, once again we
//have you covered.
//
//
//You can specify your own ID strategy by extending `PanacheEntityBase` instead of `PanacheEntity`. Then
//you just declare whatever ID you want as a public field:

ID 通常是一个敏感主题，并不是每一个人都愿意让框架处理它。您可以通过拓展来指定自己的 ID 策略，实体类继承 `PanacheEntityBase` 而不继承 `PanacheEntity`，您只需要声明 ID 字段：


[source,java]
----
@Entity
public class Person extends PanacheEntityBase {

    @Id
    @SequenceGenerator(
            name = "personSequence",
            sequenceName = "person_id_seq",
            allocationSize = 1,
            initialValue = 4)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "personSequence")
    public Integer id;

    //...
}
----

//If you're using repositories, then you will want to extend `PanacheRepositoryBase` instead of `PanacheRepository`
//and specify your ID type as an extra type parameter:

如果您正在使用仓库模式，那么您应该实现 `PanacheRepositoryBase` 接口而不是 `PanacheRepository` 接口，`PanacheRepositoryBase` 接口允许您自定义 ID 类型。

[source,java]
----
@ApplicationScoped
public class PersonRepository implements PanacheRepositoryBase<Person,Integer> {
    //...
}
----

//== Mocking
== 模拟

//=== Using the active record pattern
=== 使用活动记录模式

//If you are using the active record pattern you cannot use Mockito directly as it does not support mocking static methods,
//but you can use the `quarkus-panache-mock` module which allows you to use Mockito to mock all provided static
//methods, including your own.
//
//Add this dependency to your `pom.xml`:
如果您使用的是活动记录模式，则不能够直接使用 Mockito ，因为它不支持模拟静态方法，但是您可以使用 `quarkus-panache-mock` 模块，它允许您使用 Mockito 模拟所提供的静态方法，依赖信息如下：

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-panache-mock</artifactId>
    <scope>test</scope>
</dependency>
----


//Given this simple entity:
给定简单实体

[source,java]
----
@Entity
public class Person extends PanacheEntity {

    public String name;

    public static List<Person> findOrdered() {
        return find("ORDER BY name").list();
    }
}
----

//You can write your mocking test like this:
您可以向这样编写模拟测试

[source,java]
----
@QuarkusTest
public class PanacheFunctionalityTest {

    @Test
    public void testPanacheMocking() {
        PanacheMock.mock(Person.class);

        // Mocked classes always return a default value
        Assertions.assertEquals(0, Person.count());

        // Now let's specify the return value
        Mockito.when(Person.count()).thenReturn(23L);
        Assertions.assertEquals(23, Person.count());

        // Now let's change the return value
        Mockito.when(Person.count()).thenReturn(42L);
        Assertions.assertEquals(42, Person.count());

        // Now let's call the original method
        Mockito.when(Person.count()).thenCallRealMethod();
        Assertions.assertEquals(0, Person.count());

        // Check that we called it 4 times
        PanacheMock.verify(Person.class, Mockito.times(4)).count();// <1>

        // Mock only with specific parameters
        Person p = new Person();
        Mockito.when(Person.findById(12L)).thenReturn(p);
        Assertions.assertSame(p, Person.findById(12L));
        Assertions.assertNull(Person.findById(42L));

        // Mock throwing
        Mockito.when(Person.findById(12L)).thenThrow(new WebApplicationException());
        Assertions.assertThrows(WebApplicationException.class, () -> Person.findById(12L));

        // We can even mock your custom methods
        Mockito.when(Person.findOrdered()).thenReturn(Collections.emptyList());
        Assertions.assertTrue(Person.findOrdered().isEmpty());
        
        // Mocking a void method
        Person.voidMethod();

        // Make it throw
        PanacheMock.doThrow(new RuntimeException("Stef2")).when(Person.class).voidMethod();
        try {
            Person.voidMethod();
            Assertions.fail();
        } catch (RuntimeException x) {
            Assertions.assertEquals("Stef2", x.getMessage());
        }

        // Back to doNothing
        PanacheMock.doNothing().when(Person.class).voidMethod();
        Person.voidMethod();

        // Make it call the real method
        PanacheMock.doCallRealMethod().when(Person.class).voidMethod();
        try {
            Person.voidMethod();
            Assertions.fail();
        } catch (RuntimeException x) {
            Assertions.assertEquals("void", x.getMessage());
        }

        PanacheMock.verify(Person.class).findOrdered();
        PanacheMock.verify(Person.class, Mockito.atLeast(4)).voidMethod();
        PanacheMock.verify(Person.class, Mockito.atLeastOnce()).findById(Mockito.any());
        PanacheMock.verifyNoMoreInteractions(Person.class);
    }
}
----
//<1> Be sure to call your `verify` and `do*` methods on `PanacheMock` rather than `Mockito`, otherwise you won't know
//what mock object to pass.

<1> 请务必调用 `PanacheMock` 提供的 `verify` 方法和 `do*` 方法。而不是 `Mockito` 类中提供的方法，否则您将不知道要传递什么对象进行模拟。

//==== Mocking `EntityManager`, `Session` and entity instance methods
==== 模拟 `EntityManager` 、 `Session` 和实体实例化方法


//If you need to mock entity instance methods, such as `persist()` you can do it by mocking the Hibernate ORM `Session` object:
如果您需要模拟实体实例化方法，比如 `persist()` 方法，您可以通过模拟 Hibernate ORM Session 对象来实现：

[source,java]
----
@QuarkusTest
public class PanacheMockingTest {

    @InjectMock
    Session session;

    @BeforeEach
    public void setup() {
        Query mockQuery = Mockito.mock(Query.class);
        Mockito.doNothing().when(session).persist(Mockito.any());
        Mockito.when(session.createQuery(Mockito.anyString())).thenReturn(mockQuery);
        Mockito.when(mockQuery.getSingleResult()).thenReturn(0l);
    }

    @Test
    public void testPanacheMocking() {
        Person p = new Person();
        // mocked via EntityManager mocking
        p.persist();
        Assertions.assertNull(p.id);

        Mockito.verify(session, Mockito.times(1)).persist(Mockito.any());
    }
}
----

//=== Using the repository pattern
=== 使用仓库模式

//If you are using the repository pattern you can use Mockito directly, using the `quarkus-junit5-mockito` module,
//which makes mocking beans much easier:
如果您使用仓库模式，您可以直接使用 Mockito ，使用 `quarkus-junit5-mockito` 模块，这使得模拟 bean 更容易：

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-junit5-mockito</artifactId>
    <scope>test</scope>
</dependency>
----

//Given this simple entity:
给定简单实体

[source,java]
----
@Entity
public class Person {

    @Id
    @GeneratedValue
    public Long id;

    public String name;
}
----

//And this repository:
仓库对象：

[source,java]
----
@ApplicationScoped
public class PersonRepository implements PanacheRepository<Person> {
    public List<Person> findOrdered() {
        return find("ORDER BY name").list();
    }
}
----

//You can write your mocking test like this:
您可以向这样编写模拟测试

[source,java]
----
@QuarkusTest
public class PanacheFunctionalityTest {
    @InjectMock
    PersonRepository personRepository;

    @Test
    public void testPanacheRepositoryMocking() throws Throwable {
        // Mocked classes always return a default value
        Assertions.assertEquals(0, personRepository.count());

        // Now let's specify the return value
        Mockito.when(personRepository.count()).thenReturn(23L);
        Assertions.assertEquals(23, personRepository.count());

        // Now let's change the return value
        Mockito.when(personRepository.count()).thenReturn(42L);
        Assertions.assertEquals(42, personRepository.count());

        // Now let's call the original method
        Mockito.when(personRepository.count()).thenCallRealMethod();
        Assertions.assertEquals(0, personRepository.count());

        // Check that we called it 4 times
        Mockito.verify(personRepository, Mockito.times(4)).count();

        // Mock only with specific parameters
        Person p = new Person();
        Mockito.when(personRepository.findById(12L)).thenReturn(p);
        Assertions.assertSame(p, personRepository.findById(12L));
        Assertions.assertNull(personRepository.findById(42L));

        // Mock throwing
        Mockito.when(personRepository.findById(12L)).thenThrow(new WebApplicationException());
        Assertions.assertThrows(WebApplicationException.class, () -> personRepository.findById(12L));

        Mockito.when(personRepository.findOrdered()).thenReturn(Collections.emptyList());
        Assertions.assertTrue(personRepository.findOrdered().isEmpty());

        // We can even mock your custom methods
        Mockito.verify(personRepository).findOrdered();
        Mockito.verify(personRepository, Mockito.atLeastOnce()).findById(Mockito.any());
        Mockito.verifyNoMoreInteractions(personRepository);
    }
}
----

//== How and why we simplify Hibernate ORM mappings
== 为什么要如此简化 Hibernate ORM 的映射

//When it comes to writing Hibernate ORM entities, there are a number of annoying things that users have grown used to
//reluctantly deal with, such as:
在编写 Hibernate ORM 实体时，用户已经习惯了不情愿的处理许多令人烦恼的事情，例如：

//- Duplicating ID logic: most entities need an ID, most people don't care how it's set, because it's not really
//relevant to your model.
- 重复 ID 逻辑，大多数实体都需要一个ID，大多数人都不关心它是如何设置的，因为它与您的模型并非直接相关

- Traditional EE patterns advise to split entity definition (the model) from the operations you can do on them
(DAOs, Repositories), but really that requires a split between the state and its operations even though
we would never do something like that for regular objects in the Object Oriented architecture, where state and methods
are in the same class. Moreover, this requires two classes per entity, and requires injection of the DAO or Repository
where you need to do entity operations, which breaks your edit flow and requires you to get out of the code you're
writing to set up an injection point before coming back to use it.
- 传统 EE 模型中建议将实体定义（模型）从您可以对它们的执行操作（DAO,仓库) 中分离，单实际上这需要在状态和操作之间进行分离。

//- Hibernate queries are super powerful, but overly verbose for common operations, requiring you to write queries even
//when you don't need all the parts.
- Hibernate 查询非常强大，但对于常见操作来说过于荣昌，及时您不需要所有部分，也需要编写查询。
//- Hibernate is very general-purpose, but does not make it trivial to do trivial operations that make up 90% of our
//model usage.
- Hibernate 是非常通用的，单不会让我们的模型使用率高达 90% 的琐碎操作变得轻而易举。

//With Panache, we took an opinionated approach to tackle all these problems:
借助 Panache ，我们采取了一种自以为是的方法来解决这些问题：

//- Make your entities extend `PanacheEntity`: it has an ID field that is auto-generated. If you require
//a custom ID strategy, you can extend `PanacheEntityBase` instead and handle the ID yourself.
- 您的实体通过继承 `PanacheEntity` ： 它有一个自动生成的 ID 字段，如果宁需要自定义 ID策略，则可以继承 `PanacheEntityBase` 拓展ID。
- Use public fields. Get rid of dumb getter and setters. Hibernate ORM w/o Panache also doesn't require you to use getters and setters,
but Panache will additionally generate all getters and setters that are missing, and rewrite every access to these fields to use the accessor methods. This way you can still
write _useful_ accessors when you need them, which will be used even though your entity users still use field accesses. This implies that from the Hibernate perspective you're using accessors via getters and setters even while it looks like field accessors.
//- With the active record pattern: put all your entity logic in static methods in your entity class and don't create DAOs.
//Your entity superclass comes with lots of super useful static methods, and you can add your own in your entity class.
//Users can just start using your entity `Person` by typing `Person.` and getting completion for all the operations in a single place.
- 使用活动记录模式，将所有实体逻辑放在实体的静态方法中，不需要创建DAO。您的实体类中会携带很多有用的静态方法，您可以在实体类中增加自己想要的方法，用户只需要在一个地方输入 `Person` 即可操作实体相关内容。

//- Don't write parts of the query that you don't need: write `Person.find("order by name")` or
//`Person.find("name = ?1 and status = ?2", "stef", Status.Alive)` or even better
//`Person.find("name", "stef")`.
- 不需要编写查询部分； 编写 `Person.find("order by name")` 、 `Person.find("name = ?1 and status = ?2", "stef", Status.Alive)` 甚至于 `Person.find("name", "stef")`

//That's all there is to it: with Panache, Hibernate ORM has never looked so trim and neat.
有了 Panache Hibernate ORM 从未看起来如此简单

//== Defining entities in external projects or jars
== 在外部项目或 jar 中定义实体

//Hibernate ORM with Panache relies on compile-time bytecode enhancements to your entities.
带有 Panache 的 Hibernate ORM 依赖于对实体的编译时字节码增强。



//It attempts to identify archives with Panache entities (and consumers of Panache entities)
//by the presence of the marker file `META-INF/panache-archive.marker`. Panache includes an
//annotation processor that will automatically create this file in archives that depend on
//Panache (even indirectly). If you have disabled annotation processors you may need to create
//this file manually in some cases.

它尝试通过标记文件  `META-INF/panache-archive.marker` 来识别 Panache 实体，Panache包含一个注解处理器，它将自动以来在 Panache （或者间接依赖）。如果您禁用了注解处理器，在某些情况下需要手动创建该文件。



//WARNING: If you include the jpa-modelgen annotation processor this will exclude the Panache
//annotation processor by default. If you do this you should either create the marker file
//yourself, or add the `quarkus-panache-common` as well, as shown below:
WARNING: 如果您包含 jpa-modelgen 注解处理器，在默认情况下是排除 Panache 注解处理器。如果您这样做，您应该自己创建标记文件，或者添加 `quarkus-panache-common` 依赖，


[source,xml]
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${compiler-plugin.version}</version>
    <configuration>
      <annotationProcessorPaths>
        <annotationProcessorPath>
          <groupId>org.hibernate</groupId>
          <artifactId>hibernate-jpamodelgen</artifactId>
          <version>${hibernate.version}</version>
        </annotationProcessorPath>
        <annotationProcessorPath>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-panache-common</artifactId>
          <version>${quarkus.platform.version}</version>
        </annotationProcessorPath>
      </annotationProcessorPaths>
    </configuration>
</plugin>
----
